[theme]
primaryColor = "#5eadad"
backgroundColor = "#0f1a1a"
secondaryBackgroundColor = "#142424"
textColor = "#e0eeee"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
